services:
  gateway:
    image: onlinejudge
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - SERVICE=service-gateway

  judge:
    image: onlinejudge
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - SERVICE=service-judge

  problem:
    image: onlinejudge
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - SERVICE=service-problem

  submit:
    image: onlinejudge
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - SERVICE=service-submit

  # contest:
  #   image: onlinejudge
  #   network_mode: host
  #   volumes:
  #     - ./data:/data
  #   environment:
  #     - SERVICE=service-contest

  user:
    image: onlinejudge
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - SERVICE=service-user

  chatgpt:
    image: onlinejudge
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - SERVICE=service-chatgpt

volumes:
  oj-data:
