// Code generated by Kitex v0.7.2. DO NOT EDIT.
package problemservice

import (
	server "github.com/cloudwego/kitex/server"
	problem "main/kitex_gen/problem"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler problem.ProblemService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
