// Code generated by Kitex v0.7.2. DO NOT EDIT.

package chatgptservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
	chatgpt "main/kitex_gen/chatgpt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Chat(ctx context.Context, Req *chatgpt.ChatRequest, callOptions ...callopt.Option) (stream ChatGPTService_ChatClient, err error)
}

type ChatGPTService_ChatClient interface {
	streaming.Stream
	Recv() (*chatgpt.ChatResponse, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kChatGPTServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kChatGPTServiceClient struct {
	*kClient
}

func (p *kChatGPTServiceClient) Chat(ctx context.Context, Req *chatgpt.ChatRequest, callOptions ...callopt.Option) (stream ChatGPTService_ChatClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Chat(ctx, Req)
}
