name: Docker Build and Publish

on:
  push:
    branches:
      - master
      - docker-test
  pull_request:
    branches:
      - master
      - docker-test

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker image
        run: docker build -t onlinejudge:latest .

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker tag onlinejudge:latest $DOCKER_USERNAME/onlinejudge:latest
          docker push $DOCKER_USERNAME/onlinejudge:latest
